apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-holl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-holl@sha256:ad6b8807b7d5d62e202323a68ddfdac7ded1eae21242c4db8cd0ed200b8fb09a
        name: my-nodejs
        resources: {}
status: {}
